print("This script is designed for the Study Drills")

#print("This script is designed for the Study Drills ")
#print("This script is designed for the Study Drills")
#print("This script is designed for the Study Drills ")
#print("This script is designed for the Study Drills")
#print("This script is designed for the Study Drills ")
#print("This script is designed for the Study Drills")
#print("This script is designed for the Study Drills ")
#print("This script is designed for the Study Drills")
#print("This script is designed for the Study Drills ")